- name: Machine Name
  hosts: localhost
  vars:
    ansible_connection: network_cli
  become: yes
  become_method: enable
  tasks:
  - name: Get Machine Name
    OneFuse_get_name:
      policy_name: 'machine'
      template_properties: {
                nameGroup: 'pp',
                nameLocation: 'atl',
                nameEnv: 'p',
                nameOS: 'l',
                nameApp: 'wp'
        }
    register: name
  - name: Output Results
    debug:
      msg: '{{ name }}'